version: '2.1'

# This is starting a simple php-cli image waiting for vs code to exec a phpunit

services:
  mysql:
    image: ${MYSQL_IMAGE}:${MYSQL_VERSION_TAG}
    container_name: ${PROJECT_NAME}_db
    env_file: .env
    networks:
      phpbb:
        aliases:
          - db
    volumes:
      - ${MYSQL_DATA_FOLDER}:/var/lib/mysql
    ports:
      - ${DOCKER_PUBLIC_IP:-0.0.0.0}:${MYSQL_EXPORT_PORT}:3306

  cli:
    image: ${PHP_IMAGE}:${PHP_IMAGE_VERSION}
    container_name: ${PROJECT_NAME}_php
    depends_on:
      - mysql
    networks:
      - phpbb
    env_file: .env
    volumes:
      - ${XDEBUG_CONFIG}:${XDEBUG_CONTAINER_CONFIG}
      - ${SHARE_WEB_DIR}:${PHP_CONTAINER_WEB_DIR}
      - ${SHARE_EXTENSION_DIR}:${PHP_CONTAINER_EXTENSION_DIR}
      - ${PHPBB_CONFIG_FILE}:${PHPBB_CONTAINER_CONFIG_FILE}
      - ${PHPUNIT_SCRIPT}:${PHPUNIT_CONTAINER_SCRIPT}
    working_dir: /phpbb
    tty: true

networks:
  phpbb:
    driver: bridge
